# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_prevalence <- function(X) {
    .Call(`_PreLectR_get_prevalence`, X)
}

initialize_M <- function(X) {
    .Call(`_PreLectR_initialize_M`, X)
}

initialize_w <- function(X) {
    .Call(`_PreLectR_initialize_w`, X)
}

initialize_pvl <- function(pvlvec) {
    .Call(`_PreLectR_initialize_pvl`, pvlvec)
}

sigmoid <- function(z) {
    .Call(`_PreLectR_sigmoid`, z)
}

BCE <- function(y_true, y_pred, epsilon = 1e-8) {
    .Call(`_PreLectR_BCE`, y_true, y_pred, epsilon)
}

logistic_gradient <- function(X, y, w) {
    .Call(`_PreLectR_logistic_gradient`, X, y, w)
}

proximal_GD_clr <- function(X, y, w, v, pvl, thres, lr, alpha, epsilon) {
    .Call(`_PreLectR_proximal_GD_clr`, X, y, w, v, pvl, thres, lr, alpha, epsilon)
}

prelect_clr <- function(X, pvl, y, lmbd = 1e-5, max_iter = 10000L, tol = 1e-4, lr = 0.001, alpha = 0.9, epsilon = 1e-8, echo = FALSE) {
    .Call(`_PreLectR_prelect_clr`, X, pvl, y, lmbd, max_iter, tol, lr, alpha, epsilon, echo)
}

predict_proba <- function(X, w) {
    .Call(`_PreLectR_predict_proba`, X, w)
}

MSE <- function(y_true, y_pred, epsilon = 1e-8) {
    .Call(`_PreLectR_MSE`, y_true, y_pred, epsilon)
}

mse_gradient <- function(X, y, w) {
    .Call(`_PreLectR_mse_gradient`, X, y, w)
}

proximal_GD_reg <- function(X, y, w, v, pvl, thres, lr, alpha, epsilon) {
    .Call(`_PreLectR_proximal_GD_reg`, X, y, w, v, pvl, thres, lr, alpha, epsilon)
}

prelect_reg <- function(X, pvl, y, lmbd = 1e-5, max_iter = 10000L, tol = 1e-4, lr = 0.001, alpha = 0.9, epsilon = 1e-8, echo = FALSE) {
    .Call(`_PreLectR_prelect_reg`, X, pvl, y, lmbd, max_iter, tol, lr, alpha, epsilon, echo)
}

R2 <- function(y_true, y_pred) {
    .Call(`_PreLectR_R2`, y_true, y_pred)
}

initialize_M_multi <- function(X) {
    .Call(`_PreLectR_initialize_M_multi`, X)
}

initialize_w_multi <- function(X, n_class) {
    .Call(`_PreLectR_initialize_w_multi`, X, n_class)
}

initialize_pvl_multi <- function(pvlmat) {
    .Call(`_PreLectR_initialize_pvl_multi`, pvlmat)
}

prelect_multi_clr <- function(X, pvl, y, lmbd = 1e-5, max_iter = 10000L, tol = 1e-4, lr = 0.001, alpha = 0.9, epsilon = 1e-8, echo = FALSE) {
    .Call(`_PreLectR_prelect_multi_clr`, X, pvl, y, lmbd, max_iter, tol, lr, alpha, epsilon, echo)
}

cox_loss <- function(X, w, events) {
    .Call(`_PreLectR_cox_loss`, X, w, events)
}

cox_gradient <- function(X, w, events) {
    .Call(`_PreLectR_cox_gradient`, X, w, events)
}

proximal_GD_cox <- function(X, events, w, v, pvl, thres, lr = 0.001, alpha = 0.9, epsilon = 1e-8) {
    .Call(`_PreLectR_proximal_GD_cox`, X, events, w, v, pvl, thres, lr, alpha, epsilon)
}

prelect_cox <- function(X, pvl, events, lmbd = 1e-5, max_iter = 10000L, tol = 1e-4, lr = 0.001, alpha = 0.9, epsilon = 1e-8, echo = FALSE) {
    .Call(`_PreLectR_prelect_cox`, X, pvl, events, lmbd, max_iter, tol, lr, alpha, epsilon, echo)
}

concordance_index <- function(time, status, risk) {
    .Call(`_PreLectR_concordance_index`, time, status, risk)
}

map_ko_to_taxon <- function(KOindex) {
    .Call(`_PreLectR_map_ko_to_taxon`, KOindex)
}

GSEA_run <- function(hit_loci, refer_length) {
    .Call(`_PreLectR_GSEA_run`, hit_loci, refer_length)
}

